FROM mysql

ENV MYSQL_ROOT_PASSWORD=Luucaohoang1604^^
ENV MYSQL_DATABASE=koi_company_dev
ENV MYSQL_USER=lcaohoanq
ENV MYSQL_PASSWORD=Luucaohoang1604^^

COPY ./docs/dataV15.sql /docker-entrypoint-initdb.d/