insert into koi_company.categories (id, name)
values  (1, 'Kohaku'),
        (2, 'Taisho Sanke'),
        (3, 'Showa Sanshoku'),
        (4, 'Utsurimono'),
        (5, 'Shiro Utsuri'),
        (6, 'Hi Utsuri'),
        (7, 'Ki Utsuri'),
        (8, 'Asagi'),
        (9, 'Shusui'),
        (10, 'Bekko'),
        (11, 'Tancho'),
        (12, 'Ginrin Kohaku'),
        (13, 'Ginrin Sanke'),
        (14, 'Ginrin Showa'),
        (15, 'Doitsu Kohaku'),
        (16, 'Doitsu Sanke'),
        (17, 'Doitsu Showa'),
        (18, 'Kin Kikokuryu'),
        (19, 'Kumonryu'),
        (20, 'Ochiba Shigure');